version: '3.8'

services:

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
    - "127.0.0.1:9080:8080"
    volumes:
    - jenkins_home:/var/jenkins_home
    restart: unless-stopped


volumes:
  jenkins_home:



